module Utils.Theme exposing (Theme, lightTheme, darkTheme, getTheme)


type alias Theme =
    { toolbarBg : String
    , toolbarDeleteBg : String
    , toolbarBorderColor : String
    , btnSecondaryBg : String
    , btnDisabledBg : String
    , btnDisabledText : String
    , btnPrimary : String
    , btnGuide : String
    , btnConvert : String
    , btnDelete : String
    , btnBuildActive : String
    , btnAutoRunActive : String
    , canvasBg : String
    , rightPanelBg : String
    , rightPanelBorder : String
    , inputBg : String
    , inputText : String
    , inputBorder : String
    , overlayBorder : String
    , overlayHint : String
    , textPrimary : String
    , textSecondary : String
    , textMuted : String
    , textOnDark : String
    , dividerColor : String
    , separatorColor : String
    , consoleBg : String
    , consoleText : String
    , consoleHeaderBg : String
    , modalBg : String
    , modalTabBg : String
    , modalTabActiveBg : String
    , modalTabActiveBorder : String
    , modalSectionTitle : String
    , modalText : String
    , modalBorder : String
    , modalCodeBg : String
    , modalCodeText : String
    , modalNoteBg : String
    , modalNoteText : String
    , modalErrorBg : String
    , modalInfoBg : String
    , modalInfoText : String
    , exampleCardBg : String
    , exampleCardBorder : String
    , resultAcceptBg : String
    , resultAcceptText : String
    , resultRejectBg : String
    , resultRejectText : String
    , convStepDescBg : String
    , convSectionHeaderBg : String
    , convTableHeaderBg : String
    , settingsBg : String
    , settingsBorder : String
    , automatonTypeDfa : String
    , automatonTypeIncompleteDfa : String
    , automatonTypeNfa : String
    , automatonDefTitle : String
    , automatonDefBorder : String
    , readingHeadConsumedBg : String
    , readingHeadConsumedText : String
    , tabActiveBg : String
    , tabText : String
    , edgeColor : String
    , edgeLabelColor : String
    , convTableRowHighlight : String
    , convTableCellHighlight : String
    , convTableColHighlight : String
    , convTableColHeaderHighlight : String
    , copyBtnBg : String
    , stateFill : String
    , stateBorder : String
    , stateText : String
    , stateTransitionHighlight : String
    , tutorialVeilBg : String
    , tutorialTooltipBg : String
    , tutorialTooltipText : String
    , colorWhite : String
    , colorBlack : String
    , colorTransparent : String
    , overlayDark25 : String
    , overlayDark50 : String
    , overlayDark60 : String
    , overlayDark70 : String
    , overlayLight08 : String
    , overlayLight12 : String
    , overlayLight20 : String
    , overlayLight25 : String
    , overlayLight30 : String
    , overlayLight50 : String
    , yellowGlowShadow : String
    , toggleOnBg : String
    , toggleOffBg : String
    , accentColor : String
    , mutedContrastText : String
    , infoColor : String
    , infoColorDark : String
    , successColor : String
    , successColorDark : String
    , errorColor : String
    , errorColorDark : String
    , warningColor : String
    , neutralGrayBg : String
    , neutralGrayStroke : String
    , copyTooltipBg : String
    , relaunchBtnBg : String
    , strongBorderColor : String
    , lightDividerBorder : String
    , activeEdgeColor : String
    , highlightEdgeColor : String
    , gridStrokeColor : String
    , selectedFillColor : String
    , selectedBorderColor : String
    , editingFillColor : String
    , editingTextColor : String
    , runningFillColor : String
    , runningBorderColor : String
    , acceptFillColor : String
    , acceptBorderColor : String
    , rejectFillColor : String
    , rejectBorderColor : String
    , trailAcceptFillColor : String
    , trailRejectFillColor : String
    , conversionNewFillColor : String
    , conversionProcessedFillColor : String
    , lightTextColor : String
    , highlightBorderColor : String
    , nfaNodeBoxBg : String
    , nfaNodeBoxStroke : String
    , nfaNodeBoxText : String
    , startArrowColor : String
    }


lightTheme : Theme
lightTheme =
    { toolbarBg = "#1a2f4a"
    , toolbarDeleteBg = "#4a1a1a"
    , toolbarBorderColor = "#263238"
    , btnSecondaryBg = "#546e7a"
    , btnDisabledBg = "#78909c"
    , btnDisabledText = "#b0bec5"
    , btnPrimary = "#0277bd"
    , btnGuide = "#00796b"
    , btnConvert = "#6a1b9a"
    , btnDelete = "#c62828"
    , btnBuildActive = "#1565c0"
    , btnAutoRunActive = "#00897b"
    , canvasBg = "#ecf0f1"
    , rightPanelBg = "#f8f9fa"
    , rightPanelBorder = "#34495e"
    , inputBg = "white"
    , inputText = "#212121"
    , inputBorder = "#bdc3c7"
    , overlayBorder = "#3498db"
    , overlayHint = "#666"
    , textPrimary = "#212121"
    , textSecondary = "#424242"
    , textMuted = "#546e7a"
    , textOnDark = "white"
    , dividerColor = "#b0bec5"
    , separatorColor = "#ccc"
    , consoleBg = "#000000"
    , consoleText = "#d4d4d4"
    , consoleHeaderBg = "#1a2f4a"
    , modalBg = "white"
    , modalTabBg = "#263238"
    , modalTabActiveBg = "#37474f"
    , modalTabActiveBorder = "#4fc3f7"
    , modalSectionTitle = "#1a2f4a"
    , modalText = "#424242"
    , modalBorder = "#cfd8dc"
    , modalCodeBg = "#f5f5f5"
    , modalCodeText = "#c62828"
    , modalNoteBg = "#e8f5e9"
    , modalNoteText = "#1b5e20"
    , modalErrorBg = "#fff8f8"
    , modalInfoBg = "#f0f7ff"
    , modalInfoText = "#0d47a1"
    , exampleCardBg = "#fafafa"
    , exampleCardBorder = "#cfd8dc"
    , resultAcceptBg = "#e8f5e9"
    , resultAcceptText = "#2e7d32"
    , resultRejectBg = "#ffebee"
    , resultRejectText = "#c62828"
    , convStepDescBg = "#fffde7"
    , convSectionHeaderBg = "#e8eaf6"
    , convTableHeaderBg = "#ccc"
    , settingsBg = "#1e3a50"
    , settingsBorder = "#263238"
    , automatonTypeDfa = "#358cc7"
    , automatonTypeIncompleteDfa = "#d4a017"
    , automatonTypeNfa = "#ec7c1a"
    , automatonDefTitle = "#273646"
    , automatonDefBorder = "#359ee4"
    , readingHeadConsumedBg = "#eceff1"
    , readingHeadConsumedText = "#b0bec5"
    , tabActiveBg = "#546e7a"
    , tabText = "white"
    , edgeColor = "#222"
    , edgeLabelColor = "black"
    , convTableRowHighlight = "#fff9c4"
    , convTableCellHighlight = "#fff176"
    , convTableColHighlight = "#e3f2fd"
    , convTableColHeaderHighlight = "#90caf9"
    , copyBtnBg = "#7aa8c7"
    , stateFill = "#eceff1"
    , stateBorder = "#455a64"
    , stateText = "#000000"
    , stateTransitionHighlight = "#fff59d"
    , tutorialVeilBg = "rgba(0,0,0,0.45)"
    , tutorialTooltipBg = "#1e293b"
    , tutorialTooltipText = "#ffffff"
    , colorWhite = "white"
    , colorBlack = "#000"
    , colorTransparent = "transparent"
    , overlayDark25 = "rgba(0,0,0,0.25)"
    , overlayDark50 = "rgba(0,0,0,0.5)"
    , overlayDark60 = "rgba(0,0,0,0.6)"
    , overlayDark70 = "rgba(0,0,0,0.7)"
    , overlayLight08 = "rgba(255,255,255,0.08)"
    , overlayLight12 = "rgba(255,255,255,0.12)"
    , overlayLight20 = "rgba(255,255,255,0.2)"
    , overlayLight25 = "rgba(255,255,255,0.25)"
    , overlayLight30 = "rgba(255,255,255,0.3)"
    , overlayLight50 = "rgba(255,255,255,0.5)"
    , yellowGlowShadow = "0 0 0 3px #ffeb3b, 0 0 18px rgba(255,235,59,0.7)"
    , toggleOnBg = "#0288d1"
    , toggleOffBg = "#546e7a"
    , accentColor = "#00bcd4"
    , mutedContrastText = "#cfd8dc"
    , infoColor = "#2196F3"
    , infoColorDark = "#1565C0"
    , successColor = "#4CAF50"
    , successColorDark = "#2E7D32"
    , errorColor = "#F44336"
    , errorColorDark = "#B71C1C"
    , warningColor = "#f9a825"
    , neutralGrayBg = "#90a4ae"
    , neutralGrayStroke = "#607d8b"
    , copyTooltipBg = "#333"
    , relaunchBtnBg = "#00796b"
    , strongBorderColor = "#0d1e30"
    , lightDividerBorder = "#e0e0e0"
    , activeEdgeColor = "#e74c3c"
    , highlightEdgeColor = "#f9a825"
    , gridStrokeColor = "rgba(120,120,120,0.22)"
    , selectedFillColor = "#80cbc4"
    , selectedBorderColor = "#004d40"
    , editingFillColor = "#ffe082"
    , editingTextColor = "#1a1a1a"
    , runningFillColor = "#1e88e5"
    , runningBorderColor = "#1565c0"
    , acceptFillColor = "#43a047"
    , acceptBorderColor = "#2e7d32"
    , rejectFillColor = "#e53935"
    , rejectBorderColor = "#b71c1c"
    , trailAcceptFillColor = "#a5d6a7"
    , trailRejectFillColor = "#ef9a9a"
    , conversionNewFillColor = "#b3e5fc"
    , conversionProcessedFillColor = "#cfd8dc"
    , lightTextColor = "#222222"
    , highlightBorderColor = "#f57f17"
    , nfaNodeBoxBg = "#eceff1"
    , nfaNodeBoxStroke = "#90a4ae"
    , nfaNodeBoxText = "#37474f"
    , startArrowColor = "#1a6baa"
    }


darkTheme : Theme
darkTheme =
    { toolbarBg = "#0d1a27"
    , toolbarDeleteBg = "#2a0d0d"
    , toolbarBorderColor = "#1a2530"
    , btnSecondaryBg = "#37474f"
    , btnDisabledBg = "#455a64"
    , btnDisabledText = "#607d8b"
    , btnPrimary = "#0288d1"
    , btnGuide = "#00897b"
    , btnConvert = "#7b1fa2"
    , btnDelete = "#d32f2f"
    , btnBuildActive = "#1976d2"
    , btnAutoRunActive = "#00897b"
    , canvasBg = "#1a1f24"
    , rightPanelBg = "#1e2530"
    , rightPanelBorder = "#2a3845"
    , inputBg = "#252d36"
    , inputText = "#ecf0f1"
    , inputBorder = "#455a64"
    , overlayBorder = "#1565c0"
    , overlayHint = "#78909c"
    , textPrimary = "#ecf0f1"
    , textSecondary = "#b0bec5"
    , textMuted = "#78909c"
    , textOnDark = "white"
    , dividerColor = "#37474f"
    , separatorColor = "#37474f"
    , consoleBg = "#0a0a0a"
    , consoleText = "#d4d4d4"
    , consoleHeaderBg = "#0d1a27"
    , modalBg = "#1e2530"
    , modalTabBg = "#161f28"
    , modalTabActiveBg = "#1e3040"
    , modalTabActiveBorder = "#29b6f6"
    , modalSectionTitle = "#4fc3f7"
    , modalText = "#b0bec5"
    , modalBorder = "#2e3a47"
    , modalCodeBg = "#2a3340"
    , modalCodeText = "#ef9a9a"
    , modalNoteBg = "#1b3a20"
    , modalNoteText = "#a5d6a7"
    , modalErrorBg = "#2a1515"
    , modalInfoBg = "#0d1f35"
    , modalInfoText = "#e8f4fd"
    , exampleCardBg = "#252d36"
    , exampleCardBorder = "#2e3a47"
    , resultAcceptBg = "#1b3a20"
    , resultAcceptText = "#a5d6a7"
    , resultRejectBg = "#2a1515"
    , resultRejectText = "#ef9a9a"
    , convStepDescBg = "#2a2500"
    , convSectionHeaderBg = "#1a1d35"
    , convTableHeaderBg = "#37474f"
    , settingsBg = "#0d1a27"
    , settingsBorder = "#1a2530"
    , automatonTypeDfa = "#4fc3f7"
    , automatonTypeIncompleteDfa = "#ffd54f"
    , automatonTypeNfa = "#ffa726"
    , automatonDefTitle = "#90caf9"
    , automatonDefBorder = "#1976d2"
    , readingHeadConsumedBg = "#2a3340"
    , readingHeadConsumedText = "#546e7a"
    , tabActiveBg = "#2a3845"
    , tabText = "#ecf0f1"
    , edgeColor = "#cfd8dc"
    , edgeLabelColor = "#ecf0f1"
    , convTableRowHighlight = "#4a4300"
    , convTableCellHighlight = "#5a5000"
    , convTableColHighlight = "#0d2a4a"
    , convTableColHeaderHighlight = "#1a3a6a"
    , copyBtnBg = "#4a6a82"
    , stateFill = "#2a3545"
    , stateBorder = "#cfd8dc"
    , stateText = "#ecf0f1"
    , stateTransitionHighlight = "#7a6000"
    , tutorialVeilBg = "rgba(0,0,0,0.55)"
    , tutorialTooltipBg = "#263238"
    , tutorialTooltipText = "#ffffff"
    , colorWhite = "white"
    , colorBlack = "#000"
    , colorTransparent = "transparent"
    , overlayDark25 = "rgba(0,0,0,0.25)"
    , overlayDark50 = "rgba(0,0,0,0.5)"
    , overlayDark60 = "rgba(0,0,0,0.6)"
    , overlayDark70 = "rgba(0,0,0,0.7)"
    , overlayLight08 = "rgba(255,255,255,0.08)"
    , overlayLight12 = "rgba(255,255,255,0.12)"
    , overlayLight20 = "rgba(255,255,255,0.2)"
    , overlayLight25 = "rgba(255,255,255,0.25)"
    , overlayLight30 = "rgba(255,255,255,0.3)"
    , overlayLight50 = "rgba(255,255,255,0.5)"
    , yellowGlowShadow = "0 0 0 3px #ffeb3b, 0 0 18px rgba(255,235,59,0.7)"
    , toggleOnBg = "#0288d1"
    , toggleOffBg = "#546e7a"
    , accentColor = "#00bcd4"
    , mutedContrastText = "#cfd8dc"
    , infoColor = "#2196F3"
    , infoColorDark = "#1565C0"
    , successColor = "#4CAF50"
    , successColorDark = "#2E7D32"
    , errorColor = "#F44336"
    , errorColorDark = "#B71C1C"
    , warningColor = "#f9a825"
    , neutralGrayBg = "#90a4ae"
    , neutralGrayStroke = "#607d8b"
    , copyTooltipBg = "#333"
    , relaunchBtnBg = "#00796b"
    , strongBorderColor = "#0d1e30"
    , lightDividerBorder = "#e0e0e0"
    , activeEdgeColor = "#e74c3c"
    , highlightEdgeColor = "#f9a825"
    , gridStrokeColor = "rgba(120,120,120,0.22)"
    , selectedFillColor = "#80cbc4"
    , selectedBorderColor = "#004d40"
    , editingFillColor = "#ffe082"
    , editingTextColor = "#1a1a1a"
    , runningFillColor = "#1e88e5"
    , runningBorderColor = "#1565c0"
    , acceptFillColor = "#43a047"
    , acceptBorderColor = "#2e7d32"
    , rejectFillColor = "#e53935"
    , rejectBorderColor = "#b71c1c"
    , trailAcceptFillColor = "#a5d6a7"
    , trailRejectFillColor = "#ef9a9a"
    , conversionNewFillColor = "#b3e5fc"
    , conversionProcessedFillColor = "#cfd8dc"
    , lightTextColor = "#222222"
    , highlightBorderColor = "#f57f17"
    , nfaNodeBoxBg = "#eceff1"
    , nfaNodeBoxStroke = "#90a4ae"
    , nfaNodeBoxText = "#37474f"
    , startArrowColor = "#64b5f6"
    }


getTheme : Bool -> Theme
getTheme isDark =
    if isDark then
        darkTheme

    else
        lightTheme
